### PR TITLE
Reduction process: effective-instrument geometry.

### PR DESCRIPTION
**Pull request by ekapadi**
## Description of work

At the end of the reduction process, the instrument associated with each output workspace is modified.  A new _effective_ instrument is substituted for the instrument attached to each workspace.  This instrument has the same number of pixels as there are group-ids, and the location of each pixel is set to the mean location of the _unmasked_ original pixels participating in that pixel group.  By implication, this substitution results in there being one pixel per spectrum in each output workspace.  (An exception to this substitution is the _combined pixel-mask_ workspace, which is not modified.)

## Explanation of work

This commit includes the following changes:

  * A new `EffectiveInstrumentRecipe` implemented as a subrecipe called by `ReductionRecipe` for each grouping;

  * Modification of `ReductionIngredients` to include the _unmasked_ `PixelGroup`s;

  * Modification of `SousChef.prepReductionIngredients` to include the _unmasked_ `PixelGroup`s;

  * Modification of existing unit tests, and implementation of new unit tests to verify the new subrecipe's execution.

A known issue: `EditInstrumentGeometry` deletes, but does not regenerate the XML associated with the newly-edited instrument.  Unfortunately, this tends to generate a lot of misleading log messages when the associated workspaces are saved, and then reloaded.  This isn't so much an issue with `EditInstrumentGeometry` specifically, but rather with the Mantid instrument framework.

## To test
Existing unit tests have been modified, and new unit tests have been added to cover the new subrecipe.  A new CIS-test script has been added at `tests/cis_tests/effective_instrument_script.py`.

### Dev testing
In addition to running the unit tests, and the CIS-test script, the GUI-panels should be run for the full set of workflows.  There should be no _observable_ behavior changes.   (With the exception of the log messages associated with the new output changes, and a warning message associated with the "known issue" indicated above.)  **Note that you'll also need the _newly-saved_ output from the reduction workflow to test this PR.** 

The instrument associated with any output workspace can be examined directly.  It should now have the same number of pixels as there are spectra in the workspace.  Please see (and run through) the new  CIS-test script at: `tests/cis_tests/effective_instrument_script.py`.  
 
### CIS testing
The new changes function _automatically_ as part of the reduction process.
The instruments attached to the reduction-output workspaces should be examined, and verified to be as expected.
For comparison purposes, or in the case a work-around is required, the "application.yml" flag `reduction.output.useEffectiveInstrument` can be used to turn off the effective-instrument substitution.

## Link to EWM item

[EWM#6549](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=6549)

### Verification

- [ x] the author has read the EWM story and acceptance critera
- [ ] the reviewer has read the EWM story and acceptance criteria
- [ ] the reviewer certifies the acceptance criteria below reflect the criteria in EWM

### Acceptance Criteria

1) Where possible, all new changes are covered by unit tests.

2) Reduction output workspaces will have a new effective instrument that has the same number of pixels as there are spectra in the workspace.  (And by assumption, these workspaces will have a number of spectra that correspond to the number of group-ids in the associated grouping.)

3) The name of the effective instrument will be "SNAP_\<grouping name\>".

4) Locations of each effective pixel will correspond to those of the _unmasked_ PGP values for that pixel's group-id.  Note that `tests/cis_tests/effective_instrument_script.py` can be used to obtain and verify these values.  Mantid-workbench _instrument view_ might also be a useful way to verify this quickly.

This list is for ease of reference, and does not replace reading the EWM story as part of the review.  Verify this list matches the EWM story before reviewing.

- [ ] acceptance criterion 1
- [ ] acceptance criterion 2
- [ ] acceptance criterion 3
- [ ] acceptance criterion 4

### CODE REVIEW

**Comment by ekapadi** [comment]
I'm adding a cis-test script to help with verifying acceptance criterion #4.

**Comment by ekapadi** [comment]
I ran into a _snag_ with the acceptance criteria, so please wait to review this PR.  **There are some required Mantid changes in order to get the CIS-test to work.  :(**

**Comment by ekapadi** [comment]
Everything is now ready for review! :)

**Comment by walshmm** [comment]
Calibration and Normalization run without issue.
Reduction produces workspaces with the expected instrument name 
but I'm not seeing any instrument in the instrument view on completion of reduction
image

**Comment by walshmm** [comment]
now with the flag off the assert correctly fails when checking to see if a new instrument geometry was applied to the output
image
However after activating the flag and rerunning the cis test it seems to fail, the instrument loaded on the workspace is `None`
image

**Review by walshmm — APPROVED** [review]

**Pull request merged**
