### PR TITLE
For EWM 2429 [Defect] Investigate why threshold returned from CrystallographicInfoService results in no peaks from DetectorPeakPredictor

### PR DESCRIPTION
**Pull request by darshdinger**
**Description of work**
Will update once work is complete.

**To test:**
In order to test this fix, please rerun an algo that incorporates `DetectorPeakPredictor`.

Link to EWM item
[EWM 2429](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20%28Change%20Management%29#action=com.ibm.team.workitem.viewWorkItem&id=2429)

### CODE REVIEW

**Comment by walshmm** [comment]
tried to test this with the following script:
```
from mantid.simpleapi import *
import matplotlib.pyplot as plt
import numpy as np
import json
from snapred.backend.dao.ingredients import SmoothDataExcludingPeaksIngredients
from snapred.backend.recipe.algorithm.SmoothDataExcludingPeaksAlgo import SmoothDataExcludingPeaks
from snapred.backend.data.DataFactoryService import DataFactoryService
from snapred.backend.service.CrystallographicInfoService import CrystallographicInfoService
from snapred.backend.service.CalibrationService import CalibrationService
from snapred.backend.log.logger import snapredLogger
snapredLogger._level = 20

#diffraction calibration imports
from typing import List

#User inputs ###########################
runNumber = "58882"#58409'
cifPath = "/SNS/SNAP/shared/Calibration/CalibrantSamples/Silicon_NIST_640d.cif"
groupingFile = "/SNS/SNAP/shared/Calibration/Powder/PixelGroupingDefinitions/SNAPFocGrp_Column.lite.xml"
#######################################


dataFactoryService=DataFactoryService()
calibrationService = CalibrationService()
pixelGroupingParameters = calibrationService.retrievePixelGroupingParams(runNumber)
calibration = dataFactoryService.getCalibrationState(runNumber)
# focusGroups = reductionIngredients.reductionState.stateConfig.focusGroups

reductionIngredients = dataFactoryService.getReductionIngredients(runNumber)
ipts = reductionIngredients.runConfig.IPTS
rawDataPath = ipts + "shared/lite/SNAP_{}.lite.nxs.h5".format(reductionIngredients.runConfig.runNumber)
instrumentState = calibration.instrumentState
crystalInfoDict = CrystallographicInfoService().ingest(cifPath)
instrumentState.pixelGroupingInstrumentParameters = pixelGroupingParameters[0]
ws = "raw_data"
LoadEventNexus(Filename=rawDataPath, OutputWorkspace=ws)

ingredients = SmoothDataExcludingPeaksIngredients(instrumentState=instrumentState, crystalInfo=crystalInfoDict["crystalInfo"], smoothingParameter=0.05)

algo = SmoothDataExcludingPeaks()
algo.initialize()
algo.setProperty("Ingredients", ingredients.json())
algo.setProperty("InputWorkspace", ws)
algo.execute()

```

It error-ed out however on some [dependent code](https://github.com/neutrons/SNAPRed/blob/next/src/snapred/backend/recipe/algorithm/DiffractionSpectrumWeightCalculator.py#L35):
```
  at line 72 in '/SNS/users/wqp/git/SNAPRed/src/snapred/backend/recipe/algorithm/DiffractionSpectrumWeightCalculator.py'[0m
[31;20manalysis-node11 - 2023-09-28 15:11:58,553 - ERROR    - Mantid - Error in execution of algorithm SmoothDataExcludingPeaks:[0m
[31;20manalysis-node11 - 2023-09-28 15:11:58,553 - ERROR    - Mantid - Mantid Algorithm --  DiffractionSpectrumWeightCalculator  -- has failed -- EventWorkspace::dataY cannot return a non-const array: you can't modify the histogrammed data in an EventWorkspace![0m
[31;20manalysis-node11 - 2023-09-28 15:11:58,553 - ERROR    - Mantid -   at line 72 in '/SNS/users/wqp/git/SNAPRed/src/snapred/backend/recipe/algorithm/DiffractionSpectrumWeightCalculator.py'[0m
[31;20manalysis-node11 - 2023-09-28 15:11:58,553 - ERROR    - Mantid -   at line 75 in '/SNS/users/wqp/git/SNAPRed/src/snapred/backend/recipe/algorithm/SmoothDataExcludingPeaksAlgo.py'[0m
[31;20manalysis-node11 - 2023-09-28 15:11:58,553 - ERROR    - Mantid -   caused by line 175 in '/SNS/users/wqp/git/SNAPRed/src/snapred/backend/recipe/algorithm/MantidSnapper.py'[0m
[31;20manalysis-node11 - 2023-09-28 15:11:58,553 - ERROR    - Mantid -   caused by line 157 in '/SNS/users/wqp/git/SNAPRed/src/snapred/backend/recipe/algorithm/MantidSnapper.py'[0m
RuntimeError: Mantid Algorithm --  DiffractionSpectrumWeightCalculator  -- has failed -- EventWorkspace::dataY cannot return a non-const array: you can't modify the histogrammed data in an EventWorkspace!
  at line 72 in '/SNS/users/wqp/git/SNAPRed/src/snapred/backend/recipe/algorithm/DiffractionSpectrumWeightCalculator.py'
  at line 75 in '/SNS/users/wqp/git/SNAPRed/src/snapred/backend/recipe/algorithm/SmoothDataExcludingPeaksAlgo.py'
  caused by line 175 in '/SNS/users/wqp/git/SNAPRed/src/snapred/backend/recipe/algorithm/MantidSnapper.py'
  caused by line 157 in '/SNS/users/wqp/git/SNAPRed/src/snapred/backend/recipe/algorithm/MantidSnapper.py'
  File "<string>", line 44, in <module>
```

**Comment by rboston628** [comment]
According to @mguthriem , the method used for the threshold should be the same used in `DetectorPeakPredictor`, as in [here](https://github.com/neutrons/SNAPRed/blob/8b1e8ec07a841a0c6cc18cda5a384b3766615145/src/snapred/backend/recipe/algorithm/DetectorPeakPredictor.py#L54).

**Comment by darshdinger** [comment]
> According to @mguthriem , the method used for the threshold should be the same used in `DetectorPeakPredictor`, as in [here](https://github.com/neutrons/SNAPRed/blob/8b1e8ec07a841a0c6cc18cda5a384b3766615145/src/snapred/backend/recipe/algorithm/DetectorPeakPredictor.py#L54).

So that calculation within `DetectorPeakPredictor` is already used on L43. The issue is with the median and not that calculation.

**Comment by mguthriem** [comment]
I don't where using the median as a definition came from. I'd like to consolidate on what @rboston628 linked to in `DetectorPeakPredictor` i.e.

```A = fSquared * multiplicity * dSpacing**4
        thresholdA = np.max(A) * self.getProperty("PeakIntensityThreshold").value```

**Comment by rboston628** [comment]
Why are there 48 files changed on this?

**Pull request closed without merging**
