### PR TITLE
Added an action prompt to be used to notify and ask users for permiss…

### PR DESCRIPTION
**Pull request by walshmm**
…ion to do an action

then added said prompt to areas in need
also moved the iterate button
and added the reset button function to normalizationworkflow

## Description of work
4060:
This was a two line change that just moved the iteration button to the assess step

4061:
This creates an ActionPrompt at the end of a workflow that notifies the user they have completed the workflow,
In addition it hard resets the form and clears all workspaces.

4064:
When you hit the cancel button for a workflow it will prompt you to clear all workspaces and reset the form.
Hitting continue in fact clears all workspaces.

4070:
This is as above but in the NormalizationWorkflow, as in the hackathon it just closed the window.

## Explanation of work

The action prompt is a simple window implementation with a question and answer type setup.

Confirm with the user and execute a lambda, close
Get denied by a user, close.

This is pretty flexible and solves a few action items.

## To test

Run the Gui and try out the:
Iterate Button
Cancel Button
Completing a Workflow
Normalization Cancel Button

```
On analysis.sns.gov
From SNAPRed directory and environment
python -m snapred
Open "Test Panel" and enter:
Run Number: 46680
Convergence Threshold: 0.1
Peak Intensity Threshold: 0.0001
Bins Across Peak Width: 10
Sample: Diamond_001.json
Grouping File: column lite
```

## Link to EWM item

[EWM#4060](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=4060)
[EWM#4061](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=4061)
[EWM#4064](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=4064)
[EWM#4070](https://ornlrse.clm.ibmcloud.com/ccm/web/projects/Neutron%20Data%20Project%20(Change%20Management)#action=com.ibm.team.workitem.viewWorkItem&id=4070)

### CODE REVIEW

**Comment by rboston628** [comment]
The iterate button appears on the Assessing tab.  Clicking iterate goes back to beginning with data pre-loaded.
image

Clicking forward congratulates me on completing my quest.  I think it should have here an 8-bit depiction of a knight or a sword or a princess or something, but not a blocking request.
image

Clicking "Continue"... deletes everything... absolutely everything, before I have the chance to save the assessment.  Also, now the GroceryService cache is in the state of thinking the workspaces were already loaded, giving this error if I try to run again.
image

**Comment by rboston628** [comment]
I got this far in testing, however I am stymied by not having write permissions on the analysis cluster.  There is no longer a pop-up at the saving screen, so that I can interact with the save form.
image

Clicking "Cancel" led me directly back to the start of the form, with all workspaces deleted.  Every single workspace.  It did not raise a pop-up first.
image

**Review by rboston628 — APPROVED** [review]
I tested all of this functionality and it works as described.

**Comment by rboston628** [comment]
I still oppose deleting all of the workspaces, but @mguthriem has confirmed this is desired behavior.

**Review by rboston628 — APPROVED** [review]
It's still good, had to correct a merge error that should not impact functionality.

**Comment by mguthriem** [comment]
@rboston628 I agree it would have been better to be more selective than deleting everything but, after discussing with @walshmm, this would have been extra work and will have to be delayed to phase 3.

**Pull request merged**
